POST http://localhost:3000/movies
Content-Type: application/json

{
  "first_name": "Shin-hye",
  "last_name": "Park",
  "known_for": "You're Beautiful",
  "gender": "female",
  "age": 31
}

###
PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
  "title": "koe no katachi"
}

###
GET http://localhost:3000/movies