POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Shin-hye",
  "last_name": "Park",
  "known_for": "You're Beautiful",
  "gender": "female",
  "age": 31
}

###
PATCH http://localhost:3000/actors/11
Content-Type: application/json

{
  "age": 31
}